[package]
name = "scraper-example"
version = "0.1.0"
authors = ["Timothy <2779546+Its-its@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1.0.124"
serde_json = "1.0.64"
serde_derive = "1.0.124"

reqwest = "0.11.2"
anyhow = "1.0.38"
thiserror = "1.0.24"

tokio = { version = "1.3.0", features = ["full"] }

# ffmpeg-next = "4.3.8"
regex = "1.4.5"
url = "2.2.1"
mime = "0.3.16"
rust-crypto = "0.2.36"

scraper = { version = "0.1.0", path = "../scraper" }
scraper-macros = { version = "0.1.0", path = "../macro" }