[package]
name = "scraper-example"
version = "0.1.0"
authors = ["Timothy <2779546+Its-its@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = "0.11.2"

tokio = { version = "1.3.0", features = ["full"] }

scraper = { version = "0.1.0", path = "../scraper" }
scraper-macros = { version = "0.1.0", path = "../macro" }