[package]
name = "scraper"
version = "0.1.0"
authors = ["Timothy <2779546+Its-its@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
thiserror = "1.0.24"

xpath = { git = "http://192.168.1.50:3000/Its/rust-xpath.git", version = "0.1.4" }